version: "3"
services:
  webapp:
    build: ./webapp
    depends_on:
      - movies_db
    ports:
      - 8000:8000
  syncer:
    build: ./syncer
    depends_on:
      - movies_db
  movies_db:
      image: mongo:latest
      container_name: movies_db
      environment:
        MONGO_INITDB_DATABASE: movies_db
        MONGO_INITDB_ROOT_USERNAME: movies_user
        MONGO_INITDB_ROOT_PASSWORD: movies_password
      expose:
        - "27017"
