

COMPONENT_NAME = "PyFlix WebApp"


STRICT_SLASHES = False

HOST = "0.0.0.0"
PORT = 8000

MOVIES_ENDPOINT = "/movies"
MOVIES_TEMPLATE_FILENAME = "movies.html"
MOVIES_TEMPLATE_SERVICE_PARAMETER_NAME = "service_name"
MOVIES_TEMPLATE_MOVIES_PARAMETER_NAME = "movies"


MONGODB_HOST = "movies_db"
MONGODB_PORT = 27017
MONGODB_USERNAME = "movies_user"
MONGODB_PASSWORD = "movies_password"
MONGODB_DATABASE_NAME = "movies_db"
MONGODB_MOVIES_COLLECTION_NAME = "movies"
